### ISSUE TITLE
OpenMRS does not start

### ISSUE THREAD

**Issue by MrSerWin** [theanandankit/openmrs-keycloak-dockerized-setup#1]
OpenMRS does not work after calling command docker-compose up. 
http://localhost:8080/openmrs displays erron "Can't access to webpage" - standart Google chrome error if website is unreachable

**Comment by theanandankit** [comment]
@MrSerWin, could you please share the log? Please make sure that you have cloned the complete repository and then called docker-compose up because it depends on some files.

**Comment by MrSerWin** [comment]
@theanandankit attached
[keycloak.log](https://github.com/theanandankit/openmrs-keycloak-dockerized-setup/files/7879330/keycloak.log)

**Comment by MrSerWin** [comment]
[keycloak_2.log](https://github.com/theanandankit/openmrs-keycloak-dockerized-setup/files/7879687/keycloak_2.log)

**Comment by theanandankit** [comment]
@MrSerWin and what happen if you hit the localhost:8080/openmrs, can you please share the screenshot also?

**Comment by MrSerWin** [comment]
![Снимок экрана 2022-01-17 в 10 16 01](https://user-images.githubusercontent.com/3417913/149724487-1f6e4ce4-c989-4da6-8c9a-588a40e9c540.png)
ERR_CONNECTION_REFUSED

**Comment by MrSerWin** [comment]
the same problem on another PC
![Снимок экрана 2022-01-17 в 10 42 34](https://user-images.githubusercontent.com/3417913/149728063-68963330-500a-47da-a533-1776bdbdd599.png)

**Comment by MrSerWin** [comment]
```
 Unable to find a runtime properties file at /usr/local/tomcat/openmrs-runtime.properties
Unable to find properties file: /usr/local/tomcat/.OpenMRS/openmrs-runtime.properties


WARN - InitializationFilter.verifyConnection(990) |2022-01-17T07:41:54,660| Error while checking the connection user account

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.

at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.21.jar:8.0.21]

at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.21.jar:8.0.21]

at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.21.jar:8.0.21]

at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.21.jar:8.0.21]

at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.21.jar:8.0.21]

at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:906) ~[mysql-connector-java-8.0.21.jar:8.0.21]

at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:831) ~[mysql-connector-java-8.0.21.jar:8.0.21]

at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456) ~[mysql-connector-java-8.0.21.jar:8.0.21]

at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.21.jar:8.0.21]

at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:197) ~[mysql-connector-java-8.0.21.jar:8.0.21]

at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[?:1.8.0_212]

at java.sql.DriverManager.getConnection(DriverManager.java:247) ~[?:1.8.0_212]

at org.openmrs.web.filter.initialization.InitializationFilter.verifyConnection(InitializationFilter.java:980) [openmrs-web-2.4.3.jar:?]

at org.openmrs.web.filter.initialization.InitializationFilter.access$400(InitializationFilter.java:80) [openmrs-web-2.4.3.jar:?]

at org.openmrs.web.filter.initialization.InitializationFilter$InitializationCompletion$1.run(InitializationFilter.java:1501) [openmrs-web-2.4.3.jar:?]

at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure


The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_212]

at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_212]

at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_212]

at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_212]

at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.21.jar:8.0.21]

at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.21.jar:8.0.21]

at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.21.jar:8.0.21]

at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167) ~[mysql-connector-java-8.0.21.jar:8.0.21]

at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:538) ~[mysql-connector-java-8.0.21.jar:8.0.21]

at com.mysql.cj.protocol.a.NativeProtocol.readServerCapabilities(NativeProtocol.java:490) ~[mysql-connector-java-8.0.21.jar:8.0.21]

at com.mysql.cj.protocol.a.NativeProtocol.beforeHandshake(NativeProtocol.java:377) ~[mysql-connector-java-8.0.21.jar:8.0.21]

at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1340) ~[mysql-connector-java-8.0.21.jar:8.0.21]

at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.21.jar:8.0.21]

at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:850) ~[mysql-connector-java-8.0.21.jar:8.0.21]

... 10 more

Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.

at com.mysql.cj.protocol.FullReadInputStream.readFully(FullReadInputStream.java:67) ~[mysql-connector-java-8.0.21.jar:8.0.21]

at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:63) ~[mysql-connector-java-8.0.21.jar:8.0.21]

at com.mysql.cj.protocol.a.SimplePacketReader.readHeader(SimplePacketReader.java:45) ~[mysql-connector-java-8.0.21.jar:8.0.21]

at com.mysql.cj.protocol.a.NativeProtocol.readMessage(NativeProtocol.java:532) ~[mysql-connector-java-8.0.21.jar:8.0.21]

at com.mysql.cj.protocol.a.NativeProtocol.readServerCapabilities(NativeProtocol.java:490) ~[mysql-connector-java-8.0.21.jar:8.0.21]

at com.mysql.cj.protocol.a.NativeProtocol.beforeHandshake(NativeProtocol.java:377) ~[mysql-connector-java-8.0.21.jar:8.0.21]

at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1340) ~[mysql-connector-java-8.0.21.jar:8.0.21]

at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.21.jar:8.0.21]

at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:850) ~[mysql-connector-java-8.0.21.jar:8.0.21]

... 10 more

```

**Comment by theanandankit** [comment]
@MrSerWin Working fine in my System. I'm checking why you are facing this problem.

**Comment by theanandankit** [comment]
@MrSerWin Did you try to run docker-compose in linux OS because its working fine in linux distribution OS? I think you are using windows right?

**Comment by MrSerWin** [comment]
I used Windows and MacOS . problem is the same for both

**Comment by theanandankit** [comment]
@MrSerWin Did you change the docker-compose file because i can't see `openmrs-referenceapplication-mysql` container initialization in the log file shared by you?

**Comment by MrSerWin** [comment]
yes I changet it, but after facing with this problem

**Comment by theanandankit** [comment]
No, don't change the docker-compose file. it will break the initialization. Please follow the same instruction as mentioned in [README.md](https://github.com/theanandankit/openmrs-keycloak-dockerized-setup/blob/master/README.md) file. At the time of initialization, OpenMRS and Keycloak need to setup the connection with MySQL Database ([Here](https://github.com/theanandankit/openmrs-keycloak-dockerized-setup/blob/e6a8be52988ea52ede809616215f5c686e4340a6/docker-compose.yml#L28)).

**Comment by MrSerWin** [comment]
I pulled clear data and downloaded docker images again, but prolem is actual anyway.

**Comment by theanandankit** [comment]
@MrSerWin Can you please share the log (without changing anything in docker-compose) and also the Screenshot (when hit localhost:8080/openmrs).

**Comment by MrSerWin** [comment]
@theanandankit 

![Снимок экрана 2022-01-17 в 18 07 36](https://user-images.githubusercontent.com/3417913/149794067-22f0aefe-1698-497b-87c1-c4cfc5870dc2.png)
[key.log](https://github.com/theanandankit/openmrs-keycloak-dockerized-setup/files/7882816/key.log)

**Comment by theanandankit** [comment]
@MrSerWin why am i still not able to see the MySQL instance in the log file?

 If you see the docker compose file, you will notice we have three instances (openmrs-referenceapplication-mysql, openmrs-referenceapplication, keycloak). You are facing this problem because you are not instantiating the `openmrs-referenceapplication-mysql` and `openmrs-referenceapplication` instance is not able to setup the connection with MySQL database. 

[docker.log](https://github.com/theanandankit/openmrs-keycloak-dockerized-setup/files/7886115/docker.log) this is my log file.

**Comment by MrSerWin** [comment]
Hello @theanandankit can you please contact me via skype (Mr_Ser_Win). I need your help here
thanks in advance

**Comment by theanandankit** [comment]
@MrSerWin pls ping me here https://talk.openmrs.org/u/theanandankit
